# Site settings
title: Alexej Bohr
email: alexej.bohr@gmail.com

baseurl: "." # the subpath of your site, e.g. /blog/
relative_url: "../"
url: "http://jekyll.github.io" # the base hostname & protocol for your site
github_username:  alexej-bohr

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
